Importation des bibliothèques

In [8]:
import pandas as pd

Constante

In [9]:
# chemin pour accéder aux données
FILE_PATH = '../src/data/donnees_immobilieres.parquet'

Application

| Nom de colonne                 | Description |
|--------------------------------|-------------|
| region                         | Région où se situe le bien |
| ue                             | Identifiant de l’Unité économique (Site). À compter du 31/10/2015, remplacé par l’ID unique du bien |
| id                             | Identifiant unique du bien |
| type                           | Usage majoritaire du bien |
| fonction                       | Usage majoritaire détaillé du bien |
| designation_batiment_terrain   | Désignation du bâtiment ou terrain |
| dept                           | Code du département de situation du bien |
| adresse                        | Adresse normalisée du bien |
| code_postal                    | Code postal de situation du bien |
| ville                          | Ville de situation du bien |
| pays                           | Pays de situation du bien |
| ministere                      | Ministère occupant le bien |
| date_inventaire                | Date de l’inventaire |

In [10]:
# Chargement du DataFrame depuis le fichier Parquet 
df = pd.read_parquet(FILE_PATH)

In [11]:
df.head()

,region,ue,id,type,fonction,designation_batiment_terrain,dept,adresse,code_postal,ville,pays,ministere,date_inventaire
0,CORSE,a19e7cbea4c2dae3cfca703bda49e466,936465ba5b332c60491f6cba50a76b49,biens du ministère de l'Intérieur,biens du ministère de l'Intérieur,biens du ministère de l'Intérieur,2B,None,None,None,France,"Intérieur, Outre-mer et Collec. terr.",2014-03
1,NORD-PAS DE CALAIS,c1fb47969da8dd1a5a1a93ae33245ced,44b7ec415ee6f810d44fda9c8c585069,biens du ministère de l'Intérieur,biens du ministère de l'Intérieur,biens du ministère de l'Intérieur,62,None,None,None,France,Intérieur - Outre-mer - Collectivités territor...,2015-10
2,ILE DE France,120994,IG00100036786,Espace naturel,Terrain en friche,MIN de Rungis,94,LD LA BUTTE DE CHEVILLY,94260,Fresnes,France,Services du Premier ministre,2014-03
3,RHONE ALPES,152769,IB00100093449,Bâtiment technique,Bâtiment technique,GENDARMERIE DE SAINT GENIS LAVAL,69,92 Avenue MAL FOCH,69000,SAINT-GENIS-LAVAL,France,France Domaine,2013-05
4,BASSE NORMANDIE,126681,IB00100205180,Bâtiment technique,Dépôt d'archives,ARCHIVES JUSTICE CALVADOS (pré-archivage judic...,14,R NICEPHORE NIEPCE,14120,Mondeville,France,Justice,2017-12

In [12]:
# Informations générales sur le DataFrame 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   region                        10000 non-null  object
 1   ue                            9703 non-null   object
 2   id                            10000 non-null  object
 3   type                          10000 non-null  object
 4   fonction                      10000 non-null  object
 5   designation_batiment_terrain  10000 non-null  object
 6   dept                          9998 non-null   object
 7   adresse                       6712 non-null   object
 8   code_postal                   6985 non-null   object
 9   ville                         6972 non-null   object
 10  pays                          10000 non-null  object
 11  ministere                     10000 non-null  object
 12  date_inventaire               10000 non-null  object
dtypes: object(13)
memory usage: 1015.8+ KB

In [13]:
# Statistiques descriptives pour les données numériques
df.describe()

,region,ue,id,type,fonction,designation_batiment_terrain,dept,adresse,code_postal,ville,pays,ministere,date_inventaire
count,10000,9703,10000,10000,10000,10000,9998,6712,6985,6972,10000,10000,10000
unique,25,5110,9041,18,107,5515,110,5697,2310,3775,91,46,6
top,ILE DE France,110056,IG00100014766,Espace naturel,biens du ministère de l'Intérieur,biens du ministère de l'Intérieur,13,LD LE BOURG,85460,La Faute-sur-Mer,France,Ecologie - Développement durable - Energie - A...,2013-05
freq,1171,54,4,3887,2989,2989,326,20,127,54,9823,2518,1881

In [14]:
# Dimensions du DataFrame 
print(f"Nombre de lignes : {df.shape[0]}")
print(f"Nombre de colonnes : {df.shape[1]}")

Nombre de lignes : 10000
Nombre de colonnes : 13